// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4F6dt1uAL6oCgDXQohYdd69tMX4ot6vs',
    appId: '1:738438674511:web:c385719817ad026222123a',
    messagingSenderId: '738438674511',
    projectId: 'komunidad-health-log',
    authDomain: 'komunidad-health-log.firebaseapp.com',
    storageBucket: 'komunidad-health-log.firebasestorage.app',
    measurementId: 'G-WNMSZQRSNJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv7RD2iO8PezuzeUz9m7M5e4W3p4aecLE',
    appId: '1:738438674511:android:42ee19be7253dcde22123a',
    messagingSenderId: '738438674511',
    projectId: 'komunidad-health-log',
    storageBucket: 'komunidad-health-log.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwo7ymlykmbxICO_59vTwXPfjr1mvdbts',
    appId: '1:738438674511:ios:6cbff15b6640412c22123a',
    messagingSenderId: '738438674511',
    projectId: 'komunidad-health-log',
    storageBucket: 'komunidad-health-log.firebasestorage.app',
    iosBundleId: 'com.example.klhPrototype2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwo7ymlykmbxICO_59vTwXPfjr1mvdbts',
    appId: '1:738438674511:ios:6cbff15b6640412c22123a',
    messagingSenderId: '738438674511',
    projectId: 'komunidad-health-log',
    storageBucket: 'komunidad-health-log.firebasestorage.app',
    iosBundleId: 'com.example.klhPrototype2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4F6dt1uAL6oCgDXQohYdd69tMX4ot6vs',
    appId: '1:738438674511:web:fff2a4dbdd0a2d2a22123a',
    messagingSenderId: '738438674511',
    projectId: 'komunidad-health-log',
    authDomain: 'komunidad-health-log.firebaseapp.com',
    storageBucket: 'komunidad-health-log.firebasestorage.app',
    measurementId: 'G-TWTM02Z9C2',
  );
}
